/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exportarexcel2;

import javax.swing.JTable;//tabla
import javax.swing.table.DefaultTableModel;//diseño de tabla

import org.apache.poi.ss.usermodel.Cell;//celdas
import org.apache.poi.ss.usermodel.Row;//filas
import org.apache.poi.ss.usermodel.Sheet;//hojas
import org.apache.poi.ss.usermodel.Workbook;//archivo excel
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import javax.swing.DefaultComboBoxModel;


/**
 *
 * @author MARTHA
 */
public class TablaExportra extends javax.swing.JFrame {
   
    private DefaultComboBoxModel<Personas> modelo = new DefaultComboBoxModel<Personas>();
    private DefaultTableModel modeloTabla = new DefaultTableModel();
    int total=0;
    /**
     * Creates new form TablaExportra
     */
    public TablaExportra() {
        agregarModeloTabla();
        llenarModeloComboBox();
        initComponents();
        setLocationRelativeTo(null);
        
    }
 
    
    
    private void agregarModeloTabla(){
        modeloTabla.addColumn("Seccion");
        modeloTabla.addColumn("Nombre");
        modeloTabla.addColumn("Precio");
        modeloTabla.addColumn("Direccion");
        
    }
    
    private void llenarModeloComboBox(){
        modelo.addElement(new Personas("Ferreteria","Serrucho","17000","Otanche"));
        modelo.addElement(new Personas("Papeleria","Serrucho","7000","Otanche"));
        modelo.addElement(new Personas("Armas","Serrucho","18000","Otanche"));
        modelo.addElement(new Personas("Dulces","Serrucho","27000","Otanche"));
        modelo.addElement(new Personas("Paquetes","Serrucho","34000","Otanche"));
        modelo.addElement(new Personas("Ferreteria","Serrucho","45000","Otanche"));
        modelo.addElement(new Personas("Ferreteria","Serrucho","56000","Otanche"));
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        Imprimir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        ComboPersonas = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        EtiquetaTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(580, 480));
        setResizable(false);
        setSize(new java.awt.Dimension(575, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable1.setModel(modeloTabla);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 565, 210));

        jButton1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton1.setText("Excel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 364, -1, -1));

        Imprimir.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Imprimir.setText("Imprimir");
        Imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImprimirActionPerformed(evt);
            }
        });
        getContentPane().add(Imprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(404, 364, 128, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setText("Factura");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        ComboPersonas.setModel(modelo);
        getContentPane().add(ComboPersonas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 39, 222, -1));

        jButton2.setText("Insertar Producto");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(424, 39, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 173, 565, 10));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Total: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, -1, -1));

        EtiquetaTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(EtiquetaTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        try{
            
            Workbook wb = new XSSFWorkbook();//es un objeto de alto nivel
            //de un archivo y nos permite leer o escribir un libro de trabajo
            
            Sheet sheet = wb.createSheet("customer");//creamos una hoja en
            //el archivo excel
            
            Row rowCol = sheet.createRow(0);//creamos una fila, le decimos
            //que cree una fila en la hoja que creamos(sheet), y esta fila
            //sera la 0
            
            for(int i=0;i<jTable1.getColumnCount();i++){//contamos
                //cuantas columnas tiene nuestra tabla creada
                Cell cell = rowCol.createCell(i);//entonces desde la 0
                //hasta las columnas que tenga nuestra tabla, empezamos a
                //crear celdas le decimos que cree celda en la fila,
                //creamos celdas hasta igual de columnas que hayan
                
                cell.setCellValue(jTable1.getColumnName(i));//una vez 
                //creada la celda, llamamos la funcion setCellValue, que funciona
                //para colocar un valor a la celda creada, y entonces utilizamos
                //el Nombre, o valor que hay en nuestra jTable en la columna[i]
                
            }//Esto solo para las columnas
            
            for(int j=0;j<jTable1.getRowCount();j++){//contamos cuantas filas
                //hay en nuestra tabla
                
                Row row = sheet.createRow(j+1);//creamos filas en nuestra hoja
                //creada (sheet)
                
                for(int k=0;k<jTable1.getColumnCount();k++){//contamos las columnas
                    //que hay en nuestra jTable
                    
                    Cell cell = row.createCell(k);//Creamos celdas en las filas que hayan
                    
                    //ya que es un bucle anidado, primero se recorre este for(), y poco a 
                    //poco va recorriendo el de afuera, entonces vamos creando celdas
                    //primero por todas las columnas, y poco a poco vamos avanzando en las filas
                    //que es con el bucle de "j"
                    
                    if(jTable1.getValueAt(j,k) != null){//si el valor de las celdas
                        //j,k es diferente de null, o sea, si hay algo dentro de ellas
                        
                        cell.setCellValue(jTable1.getValueAt(j,k).toString());//creamos una celda
                        //y le colocamos como valor lo que hay dentro de la celda (j,k)j representa
                        //las filas y k las columnas, y este valor lo pasamos a String
                        
                        
                    }
                    
                }
                
            }
            FileOutputStream out = new FileOutputStream(new File("C:\\Users\\MARTHA\\Desktop\\Ejemplo.xlsx"));
            //creamos un archivo de FileOutputStream, esto para sacar el archivo, y le decimos
            //que lo guarde en el escritorio
            wb.write(out);//ahora le decimos que el archivo de trabajo creado, escriba todo en el
            //archivo que vamos a sacar
            
            wb.close();//Cerramos el archivo de trabajo para los recursos
            
            out.close();//Cerramos el archivo creado
            
            System.out.println("Archivo Creado");
        }catch(FileNotFoundException ex){
            
        }catch(IOException ex1){
            System.err.println("Error, "+ex1);
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImprimirActionPerformed
        // TODO add your handling code here:
        
        try{
            
            jTable1.print();
            
        }catch(Exception e){
            
            System.err.println("Error"+e);
        }
        
    }//GEN-LAST:event_ImprimirActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        Personas p =(Personas)ComboPersonas.getSelectedItem();
        
        String seccion = p.getSeccion();
        String nombre = p.getNombre();
        String precio = p.getPrecio();
        String direccion = p.getDireccion();
        
        String [] persona={seccion,nombre,precio,direccion};
        
        total += Integer.parseInt(precio);
        
        EtiquetaTotal.setText(String.valueOf(total));
        
        modeloTabla.addRow(persona);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TablaExportra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TablaExportra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TablaExportra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TablaExportra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TablaExportra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Personas> ComboPersonas;
    private javax.swing.JLabel EtiquetaTotal;
    private javax.swing.JButton Imprimir;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
